version: "3.9"
 
services:
  nsfw-api:
    build: .
    container_name: nsfw-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=NSFW-API/NSFW_Wan_14b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
